# Configuration for split nodes
# Activate with the env variable SPLIT_NODES=true

services:
  batch-poster:
    profiles: [split-nodes]
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    image: "${NITRO_DOCKER_IMAGE_TAG}"
    ports:
      - "127.0.0.1:8149:${NITRO_PORT}"
      - "127.0.0.1:9642:9642"
    volumes:
      - "./chainConfig/batch-poster:/home/user/.arbitrum"
    command:
      - --conf.file=/home/user/.arbitrum/batch-poster-config.json
      - --node.feed.output.enable
      - --node.feed.output.port=9642

  staker:
    profiles: [split-nodes]
    depends_on:
      - batch-poster
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    image: "${NITRO_DOCKER_IMAGE_TAG}"
    ports:
      - "127.0.0.1:8249:${NITRO_PORT}"
    volumes:
      - "./chainConfig/staker:/home/user/.arbitrum"
    command:
      - --conf.file=/home/user/.arbitrum/staker-config.json
      - --execution.forwarding-target=http://batch-poster:8449
      - --node.feed.input.url=ws://batch-poster:9642

  rpc:
    profiles: [split-nodes]
    depends_on:
      - batch-poster
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    image: "${NITRO_DOCKER_IMAGE_TAG}"
    ports:
      - "127.0.0.1:${NITRO_PORT}:${NITRO_PORT}"
    volumes:
      - "./chainConfig/rpc:/home/user/.arbitrum"
    command:
      - --conf.file=/home/user/.arbitrum/rpc-config.json
      - --execution.forwarding-target=http://batch-poster:8449
      - --node.feed.input.url=ws://batch-poster:9642